/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ElButton: typeof import('element-plus/es').ElButton
  const ElCard: typeof import('element-plus/es').ElCard
  const ElForm: typeof import('element-plus/es').ElForm
  const ElMessage: typeof import('element-plus/es').ElMessage
  const ElMessageBox: typeof import('element-plus/es').ElMessageBox
  const ElNotification: typeof import('element-plus/es').ElNotification
  const ElTable: typeof import('element-plus/es').ElTable
  const ElTag: typeof import('element-plus/es').ElTag
}
